server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3316/admin-service
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123123
    continue-on-error: true
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  redis:
    host: localhost
    port: 6380
    database: 0
    password: 123123
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0
  flyway:
    enabled: true
    clean-disabled: true
    baseline-version: 1