server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3316/admin-service
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123123
    continue-on-error: true
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
